# Built-in Android baseline.
baseProfile=android_composition

# Optional capability wrappers.
settingsCapabilityClass=
testSessionCapabilityClass=
testSequenceCapabilityClass=
stopCriteriaCapabilityClass=

# Optional service wrappers.
systemServiceClass=
stateServiceClass=
actionDerivationServiceClass=
actionSelectorServiceClass=
actionExecutionServiceClass=
oracleComposerClass=
