package nl.ou.testar.genetic.programming.strategy;

public enum AvailableReturnTypes {
    AND, CLICKACTION, DRAGACTION, DRAGACTIONSAVAILABLE, EQUALS, EQUALSTYPE, ESCAPE, GREATERTHAN, HITKEYACTION, IFTHENELSE,
    LEFTCLICKSAVAILABLE, NOT, NUMBEROFACTIONS, NUMBEROFACTIONSOFTYPE, NUMBEROFDRAGACTIONS,
    NUMBEROFLEFTCLICKS, NUMBEROFPREVIOUSACTIONS, NUMBEROFTYPEACTIONS,
    NUMBEROFUNEXECUTEDDRAGACTIONS, NUMBEROFUNEXECUTEDLEFTCLICKS,
    NUMBEROFUNEXECUTEDTYPEACTIONS, OR, PREVIOUSACTION, RANDOMACTION, RANDOMACTIONOFTYPE,
    RANDOMACTIONOFTYPEOTHERTHAN, RANDOMLEASTEXECUTEDACTION,
    RANDOMMOSTEXECUTEDACTION, RANDOMNUMBER, RANDOMUNEXECUTEDACTION, RANDOMUNEXECUTEDACTIONOFTYPE,
    STATEHASNOTCHANGED, TYPEACTION, TYPEACTIONSAVAILABLE, TYPEOFACTIONOF
}
