package nl.ou.testar.temporal.guipanel;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class ThesisPicture1 {
    private JPanel panel1;
    private JButton yesButton;
    private JButton noButton;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:97px:noGrow,left:4dlu:noGrow,fill:130px:noGrow,left:17dlu:noGrow,fill:57px:noGrow,left:8dlu:noGrow,fill:60px:noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-4473925)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Socrates is man?");
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xyw(5, 3, 2));
        final JLabel label2 = new JLabel();
        label2.setText("Question 1:");
        panel1.add(label2, cc.xy(3, 3));
        yesButton = new JButton();
        yesButton.setText("Yes");
        panel1.add(yesButton, cc.xy(7, 3));
        noButton = new JButton();
        noButton.setText("No");
        panel1.add(noButton, cc.xy(9, 3));
        final JLabel label3 = new JLabel();
        label3.setText("Question 2:");
        panel1.add(label3, cc.xy(3, 5));
        button1 = new JButton();
        button1.setText("Yes");
        panel1.add(button1, cc.xy(7, 5));
        button2 = new JButton();
        button2.setText("No");
        panel1.add(button2, cc.xy(9, 5));
        final JLabel label4 = new JLabel();
        label4.setText("Question 3:");
        panel1.add(label4, cc.xy(3, 7));
        final JLabel label5 = new JLabel();
        label5.setText("All man are mortal?");
        panel1.add(label5, cc.xyw(5, 5, 2));
        final JLabel label6 = new JLabel();
        label6.setText("Socrates is mortal?");
        panel1.add(label6, cc.xyw(5, 7, 2));
        button3 = new JButton();
        button3.setText("Yes");
        panel1.add(button3, cc.xy(7, 7));
        button4 = new JButton();
        button4.setText("No");
        panel1.add(button4, cc.xy(9, 7));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
