version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'testar'
      MYSQL_DATABASE: 'testar'
      MYSQL_USER: 'testar'
      MYSQL_PASSWORD: 'testar'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/db-init:/docker-entrypoint-initdb.d
  orientdb:
    image: orientdb:3.0.34
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_DATABASE: 'testar'
      ORIENTDB_USERNAME: 'testar'
      ORIENTDB_PASSWORD: 'testar'
    volumes:
      - ./orientdb/data:/orientdb/databases
      - ./orientdb/db-init:/orientdb/db-init
    command:
      sh /orientdb/db-init/init.sh
