package org.testar.statemodel.event;

public enum StateModelEventType {
    ABSTRACT_STATE_ADDED, ABSTRACT_STATE_CHANGED, ABSTRACT_ACTION_CHANGED, ABSTRACT_STATE_TRANSITION_ADDED, ABSTRACT_STATE_MODEL_INITIALIZED,
    ABSTRACT_STATE_MODEL_READY, ABSTRACT_STATE_TRANSITION_CHANGED,
    SEQUENCE_STARTED, SEQUENCE_MANAGER_INITIALIZED, SEQUENCE_NODE_ADDED, SEQUENCE_STEP_ADDED, SEQUENCE_NODE_UPDATED, SEQUENCE_ENDED,
  //TODO: ould be better to provide some "custom" event with extra parameters
    QLEARNING_MODEL_INITIALIZED, QLEARNING_MODEL_READY
}
