/*
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2024-2026 Open Universiteit - www.ou.nl
 * Copyright (c) 2024-2026 Universitat Politecnica de Valencia - www.upv.es
 */

package org.testar.llm.action;

import java.util.Objects;
import java.util.Set;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.testar.core.action.Action;
import org.testar.core.alayer.Color;
import org.testar.core.alayer.FillPattern;
import org.testar.core.alayer.Pen;
import org.testar.core.tag.Tags;
import org.testar.core.state.Widget;
import org.testar.core.action.CompoundAction;
import org.testar.core.action.NOP;
import org.testar.core.action.PasteText;
import org.testar.core.action.Type;
import org.testar.webdriver.action.WdRemoteTypeAction;
import org.testar.webdriver.action.WebdriverSelectListSupport;
import org.testar.core.visualizers.TextVisualizer;
import org.testar.webdriver.tag.WdTags;

import com.google.gson.Gson;
import com.google.gson.JsonParseException;

public class LlmParseActionResponse {
    protected static final Logger logger = LogManager.getLogger();

    private final Gson gson;

    public LlmParseActionResponse() {
        this(new Gson());
    }

    public LlmParseActionResponse(Gson gson) {
        this.gson = gson;
    }

    /**
     * Parses the response sent by the LLM and selects an action if the response was valid.
     * @param actions Set of actions in the current state.
     * @param responseContent The response of the LLM in plaintext.
     * @return LlmParseActionResult containing the result of the parse and the action to execute if parsing was successful.
     */
    public LlmParseActionResult parseLlmResponse(Set<Action> actions, String responseContent) {
        try {
            LlmSelectedAction llmSelectedAction = gson.fromJson(sanitizeJsonResponse(responseContent), LlmSelectedAction.class);

            Action selectedAction = getActionByIdentifier(actions, llmSelectedAction.getActionId());

            // If the selectedAction is a NOP action at this stage, parsing has likely failed.
            // Observed to happen when the LLM selects an actionId that does not exist.
            if(selectedAction instanceof NOP) {
                logger.log(Level.ERROR, "Action AbstractID not found, parsing LLM response has likely failed!: " + responseContent);
                return new LlmParseActionResult(null, LlmParseActionResult.ParseResult.INVALID_ACTION);
            }

            String input = llmSelectedAction.getInput();
            Widget widget = selectedAction.get(Tags.OriginWidget);

            // For interacting with select combobox web widgets
            // A WdSelectListAction is created to change the active value of the combobox
            if(Objects.equals(widget.get(WdTags.WebTagName, ""), "select")) {
                if(Objects.equals(input, "")) {
                    return new LlmParseActionResult(null, LlmParseActionResult.ParseResult.SL_MISSING_INPUT);
                }
                Action selectAction = WebdriverSelectListSupport.createActionForInput(widget, input);
                if (selectAction == null) {
                    logger.warn("Unable to create WdSelectListAction for select widget due to missing target.");
                    return new LlmParseActionResult(null, LlmParseActionResult.ParseResult.INVALID_ACTION);
                }
                copyIdentityTags(selectedAction, selectAction);
                return new LlmParseActionResult(selectAction, LlmParseActionResult.ParseResult.SUCCESS);
            }

            setCompoundActionInputText(selectedAction, input);
            return new LlmParseActionResult(selectedAction, LlmParseActionResult.ParseResult.SUCCESS);

        } catch(JsonParseException e) {
            logger.log(Level.ERROR, "Unable to parse response from LLM to JSON: " + responseContent);
            return new LlmParseActionResult(null, LlmParseActionResult.ParseResult.PARSE_FAILED);
        } catch(NullPointerException e) {
            logger.log(Level.ERROR, "Null response due to LLM parse response error");
            return new LlmParseActionResult(null, LlmParseActionResult.ParseResult.COMMUNICATION_FAILURE);
        } catch(Exception e) {
            logger.log(Level.ERROR, "Exception parsing LLM response");
            return new LlmParseActionResult(null, LlmParseActionResult.ParseResult.COMMUNICATION_FAILURE);
        }
    }

    /**
     * Try to sanitize markdown-style code fences sometimes generated by LLMs
     * @param responseContent
     * @return The sanitized LLM response
     */
    private String sanitizeJsonResponse(String responseContent) {
        if (responseContent == null) return null;

        if (responseContent.startsWith("```")) {
            logger.log(Level.INFO, String.format("Sanitizing Response: [%s]", responseContent));
            // Remove enclosing ```...``` or ```json...```
            responseContent = responseContent.replaceAll("(?s)^```(?:json)?\\s*", "");
            responseContent = responseContent.replaceAll("(?s)\\s*```$", "");
            logger.log(Level.INFO, String.format("Sanitized Response: [%s]", responseContent));
        }

        return responseContent;
    }

    /**
     * Retrieves an action with given actionId.
     * @param actions Set of actions to search.
     * @param actionId ActionId to search for.
     * @return Requested action if found, NOP Action if not found.
     */
    private Action getActionByIdentifier(Set<Action> actions, String actionId) {
        for(Action action : actions) {
            if(action.get(Tags.AbstractID, "").equalsIgnoreCase(actionId)) {
                return action;
            }
        }
        return new NOP();
    }

    /**
     * Sets TESTAR input text of compound Type and PasteText actions.
     * @param action CompoundAction to change.
     * @param inputText The characters to enter into the input field. Can be left empty if not applicable.
     * @return if input text changed.
     */
    private boolean setCompoundActionInputText(Action action, String inputText) {
        //TODO: Create single actions in protocol so this is not necessary?
        if(action instanceof CompoundAction) {
            for(Action innerAction : ((CompoundAction)action).getActions()) {
                if (innerAction instanceof Type || innerAction instanceof PasteText) {
                    return updateTextAction(action, innerAction, inputText);
                }
            }
        }

        return updateTextAction(action, action, inputText);
    }

    private boolean updateTextAction(Action action, Action innerAction, String inputText) {
        if(action instanceof WdRemoteTypeAction) {
            ((WdRemoteTypeAction) action).setKeys(inputText);
            return true;
        }

        innerAction.set(Tags.InputText, inputText);

        String widgetDesc = action.get(Tags.OriginWidget).get(Tags.Desc, "<no description>");
        action.set(Tags.Desc, innerAction.getClass().getSimpleName() + " '" + inputText + "' into '" + widgetDesc + "'");

        if(action.get(Tags.Visualizer) instanceof TextVisualizer) {
            TextVisualizer textVisualizer = (TextVisualizer) action.get(Tags.Visualizer);
            Pen newPen = Pen.newPen().setColor(Color.Red).setFillPattern(FillPattern.Solid).setStrokeWidth(50).build();
            action.set(Tags.Visualizer, textVisualizer.withText(inputText, newPen));
        }

        return true;
    }

    private void copyIdentityTags(Action sourceAction, Action targetAction) {
        String abstractId = sourceAction.get(Tags.AbstractID, "");
        if (!abstractId.isBlank()) {
            targetAction.set(Tags.AbstractID, abstractId);
        }

        String concreteId = sourceAction.get(Tags.ConcreteID, "");
        if (!concreteId.isBlank()) {
            targetAction.set(Tags.ConcreteID, concreteId);
        }
    }

}
