flowchart LR
    subgraph CorePolicyInterfaces["core policy interfaces"]
        CP["ClickablePolicy"]
        TP["TypeablePolicy"]
        SP["ScrollablePolicy"]
        SelP["SelectablePolicy"]
        EP["EnabledPolicy"]
        BP["BlockedPolicy"]
        WFP["WidgetFilterPolicy"]
        VP["VisiblePolicy"]
        TLP["TopLevelPolicy"]
    end

    subgraph EnginePolicyComposites["engine policy composites"]
        CCP["CompositeClickablePolicy<br/>semantics: ANY"]
        CTP["CompositeTypeablePolicy<br/>semantics: ANY"]
        CSP["CompositeScrollablePolicy<br/>semantics: ANY"]
        CSelP["CompositeSelectablePolicy<br/>semantics: ANY"]
        CEP["CompositeEnabledPolicy<br/>semantics: ALL"]
        CBP["CompositeBlockedPolicy<br/>semantics: ANY"]
        CWFP["CompositeWidgetFilterPolicy<br/>semantics: ALL"]
        CVP["CompositeVisiblePolicy<br/>semantics: ALL"]
        CTLP["CompositeTopLevelPolicy<br/>semantics: ALL"]
    end

    subgraph GenericEnginePolicyImplementations["generic policy implementations"]
        TEP["TagEnabledPolicy <br> set in platform/state logic"]
        TBP["TagBlockedPolicy <br> set in platform/state logic"]
        ConfWFP["ConfiguredWidgetFilterPolicy <br> set in settings/state logic"]
        ZITLP["ZIndexTopLevelPolicy <br> set in state logic"]
    end

    subgraph PlatformPolicyImplementations["platform policy implementations"]
        PCP["PlatformClickablePolicy (WindowsClickablePolicy / WebdriverClickablePolicy / AndroidClickablePolicy)"]
        PTP["PlatformTypeablePolicy (WindowsTypeablePolicy / WebdriverTypeablePolicy / AndroidTypeablePolicy)"]
        PSP["PlatformScrollablePolicy (WindowsScrollablePolicy / WebdriverScrollablePolicy / AndroidScrollablePolicy)"]
        PSelP["PlatformSelectablePolicy (WindowsSelectablePolicy / WebdriverSelectablePolicy / AndroidSelectablePolicy)"]
        PVP["PlatformVisiblePolicy (WindowsVisiblePolicy / WebdriverVisiblePolicy / AndroidVisiblePolicy)"]
    end

    subgraph CustomPolicyImplementations["custom policy implementations"]
        CCPCSS["CustomClickablePolicy (CSSclasses)"]
        CTPCSS["CustomTypeablePolicy (CSSclasses)"]
    end

    subgraph SessionPolicyContext["session policy context"]
        SPC["SessionPolicyContext"]
    end

    subgraph PluginDefaults["plugin policy defaults"]
        PPC["PlatformPolicyContexts"]
    end


    PCP -. implements .-> CP
    PTP -. implements .-> TP
    PSP -. implements .-> SP
    PSelP -. implements .-> SelP
    PVP -. implements .-> VP

    TEP -. implements .-> EP
    TBP -. implements .-> BP
    ConfWFP -. implements .-> WFP
    ZITLP -. implements .-> TLP

    CCPCSS -. implements .-> CP
    CTPCSS -. implements .-> TP

    CP -- "1..n policies" --> CCP
    TP -- "1..n policies" --> CTP
    SP -- "1..n policies" --> CSP
    SelP -- "1..n policies" --> CSelP
    EP -- "1..n policies" --> CEP
    BP -- "1..n policies" --> CBP
    WFP -- "1..n policies" --> CWFP
    VP -- "1..n policies" --> CVP
    TLP -- "1..n policies" --> CTLP

    CCP --> PPC
    CTP --> PPC
    CSP --> PPC
    CSelP --> PPC
    CEP --> PPC
    CBP --> PPC
    CWFP --> PPC
    CVP --> PPC
    CTLP --> PPC

    PPC --> SPC
