# Built-in WebDriver baseline.
baseProfile=webdriver_composition

# Optional capability wrappers.
settingsCapabilityClass=
testSessionCapabilityClass=
testSequenceCapabilityClass=WebdriverParabankTestSequenceLoginCapability
stopCriteriaCapabilityClass=

# Optional service wrappers.
systemServiceClass=
stateServiceClass=
stateIdentifierServiceClass=WebdriverParabankStateIdentifierService
actionDerivationServiceClass=
actionIdentifierServiceClass=
actionSelectorServiceClass=
actionExecutionServiceClass=
oracleComposerClass=WebdriverWidgetLeafOverlapOracleComposer
