# Scriptless custom policies resource
# Additive policy composition. Multiple classes can be declared with ';'

replaceClickablePolicies=false
clickablePolicies=
replaceTypeablePolicies=false
typeablePolicies=
replaceScrollablePolicies=false
scrollablePolicies=
replaceSelectablePolicies=false
selectablePolicies=
replaceEnabledPolicies=false
enabledPolicies=
replaceBlockedPolicies=false
blockedPolicies=
replaceWidgetFilterPolicies=false
widgetFilterPolicies=WebdriverLinkDeniedFilterPolicy
replaceVisiblePolicies=false
visiblePolicies=
replaceAtCanvasPolicies=false
atCanvasPolicies=
replaceTopLevelPolicies=false
topLevelPolicies=
