# CLI generic composition profile.

systemServiceClass=
stateServiceClass=
stateIdentifierServiceClass=CliStateIdentifierService
actionDerivationServiceClass=
actionIdentifierServiceClass=
actionSelectorServiceClass=
actionExecutionServiceClass=
oracleComposerClass=

# baseProfile is intended to be platform-agnostic.
# baseProfile is selected dynamically from the effective
# SUTConnector when the CLI session starts.
baseProfile=

# Capability classes are not used in the CLI mode.
settingsCapabilityClass=
testSessionCapabilityClass=
testSequenceCapabilityClass=
stopCriteriaCapabilityClass=
