# Built-in WebDriver baseline.
baseProfile=webdriver_composition

# Optional capability wrappers.
settingsCapabilityClass=SetupStateModelSettingsCapability
testSessionCapabilityClass=
testSequenceCapabilityClass=
stopCriteriaCapabilityClass=

# Optional service wrappers.
systemServiceClass=
stateServiceClass=
stateIdentifierServiceClass=
actionDerivationServiceClass=
actionIdentifierServiceClass=
actionSelectorServiceClass=
actionExecutionServiceClass=
oracleComposerClass=
