# Scriptless custom policies resource
# Additive policy composition. Multiple classes can be declared with ';'

replaceClickablePolicies=false
clickablePolicies=WebdriverSparkClickablePolicy
replaceTypeablePolicies=false
typeablePolicies=
replaceScrollablePolicies=false
scrollablePolicies=
replaceSelectablePolicies=false
selectablePolicies=
replaceEnabledPolicies=false
enabledPolicies=
# Replace the default blocker so it does not re-block the Material UI exceptions.
replaceBlockedPolicies=true
blockedPolicies=WebdriverSparkBlockedPolicy
replaceWidgetFilterPolicies=false
widgetFilterPolicies=
replaceVisiblePolicies=false
visiblePolicies=
replaceTopLevelPolicies=false
topLevelPolicies=
