flowchart LR

    subgraph ScriptlessFlow["testar scriptless generate flow"]
        SystemService["SystemService"]
        StateService["StateService"]
        OracleEvaluationService["OracleEvaluationService <br> (invokation not implemented)"]
        ActionDerivationService["ActionDerivationService"]
        ActionSelectorService["ActionSelectorService"]
        ActionExecutionService["ActionExecutionService"]

        SequenceLifecycleCapability["SequenceLifecycleCapability"]
        StateVerdictCapability["StateVerdictCapability"]
        StopCriteriaCapability["StopCriteriaCapability"]
        StateActionIdentifierCapability["StateActionIdentifierCapability"]
    end

    SequenceLifecycleCapability -. sequence start and lifecycle .-> SystemService

    SystemService -. running system .-> StateService

    StateService -. identify state .-> StateActionIdentifierCapability
    StateService -. apply state verdicts .-> StateVerdictCapability
    StateVerdictCapability -. oracle evaluation .-> OracleEvaluationService

    StateService -. current state .-> StopCriteriaCapability
    StopCriteriaCapability -. continue inner loop .-> ActionDerivationService

    ActionDerivationService -. identify derived actions .-> StateActionIdentifierCapability
    ActionDerivationService -. derived actions .-> ActionSelectorService

    ActionSelectorService -. selected action .-> ActionExecutionService

    ActionExecutionService -. next state cycle .-> StateService
