name: Docker Build

on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push TESTAR Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the TESTAR_dev repo
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Prepare tar distribution of TESTAR with Gradle
        run: ./gradlew distTar
      - name: Build the testar chromedriver docker image
        run: docker build -t testartool/testar-chromedriver:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push TESTAR docker image to Docker Hub
        run: docker push testartool/testar-chromedriver:latest