name: TESTAR release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and release TESTAR distribution
    runs-on: ubuntu-latest
    steps:
      - name: Check out the TESTAR_dev repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

        # Build TESTAR and prepare the zip distribution
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build TESTAR with Gradle
        run: ./gradlew build
      - name: Prepare a zip distribution of TESTAR with Gradle
        run: ./gradlew distZip

        # Use WyriHaximus repo to compute a new tag (milestone)
      - name: Get Previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
      - name: Get next version
        id: semvers
        uses: 'WyriHaximus/github-action-next-semvers@master'
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Create new milestone
        id: createmilestone
        uses: 'WyriHaximus/github-action-create-milestone@master'
        with:
          title: ${{ steps.semvers.outputs.patch }}
      - name: Set milestone
        run: echo "GITHUB_MILESTONE=${{ steps.semvers.outputs.patch }}" >> $GITHUB_ENV

        # Create and upload a new TESTAR release
      - name: Create TESTAR Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: testar_v${{ env.GITHUB_MILESTONE }}
          tag_name: v${{ env.GITHUB_MILESTONE }}
          body: |
            Release notes:
            https://github.com/TESTARtool/TESTAR_dev/wiki/TESTAR-release-notes
            
            Latest W7 version (2.5.0):
            https://github.com/TESTARtool/TESTAR_dev/releases/download/v2.5.0/testar_w7_2.5.0.zip
            
            Follow the latest testar chromedriver docker image:
            https://hub.docker.com/r/testartool/testar-chromedriver
      - name: Upload TESTAR Release Asset
        id: upload_release_asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./testar/target/distributions/testar.zip
          asset_name: testar_v${{ env.GITHUB_MILESTONE }}_java11.zip
          asset_content_type: application/zip